#!/usr/bin/env node
var argv = require('minimist')(process.argv.slice(2));

var inlineData = {};
if (argv) {
	for (var key in argv) {
		if (key.indexOf("data-") === 0) {
			inlineData[key.substring(5)] = argv[key];
		}
	}
}

if (!argv || argv.length < 2 || !argv["_"] || argv["_"].length < 2 || !(argv["data"] || Object.keys(inlineData).length)) {
	console.log("Usage : variable-replacer sourcepath1 [sourcepath2 sourcepath3] destpath --data=datasource.json [--data-myvarname=value]");
}

require('./variable-replacer.js')({
	source: argv["_"].slice(0, argv["_"].length - 1),
	dest: argv["_"][argv["_"].length - 1],
	dataSource: argv["data"],
	inlineData: inlineData
});